USE [master]
GO

/****** Object:  Database [CdisMart]    Script Date: 25/07/2020 02:51:24 p. m. ******/
CREATE DATABASE [CdisMart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CdisMart', FILENAME = N'C:\Users\Angel\CdisMart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CdisMart_log', FILENAME = N'C:\Users\Angel\CdisMart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CdisMart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CdisMart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CdisMart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CdisMart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CdisMart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CdisMart] SET ARITHABORT OFF 
GO

ALTER DATABASE [CdisMart] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CdisMart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CdisMart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CdisMart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CdisMart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CdisMart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CdisMart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CdisMart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CdisMart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CdisMart] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CdisMart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CdisMart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CdisMart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CdisMart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CdisMart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CdisMart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CdisMart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CdisMart] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CdisMart] SET  MULTI_USER 
GO

ALTER DATABASE [CdisMart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CdisMart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CdisMart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CdisMart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CdisMart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CdisMart] SET QUERY_STORE = OFF
GO

USE [CdisMart]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CdisMart] SET  READ_WRITE 
GO

